// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdBcYNODOju3Jt7Ov5OyIIcu7ug48Ocp0',
    appId: '1:752644759129:android:291bdc6c171092bf411b48',
    messagingSenderId: '752644759129',
    projectId: 'productivitwo-app',
    storageBucket: 'productivitwo-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZendUmvo0BWckPd-TOEkKfbptodLHCvE',
    appId: '1:752644759129:web:871009d70bcc1053411b48',
    messagingSenderId: '752644759129',
    projectId: 'productivitwo-app',
    authDomain: 'productivitwo-app.firebaseapp.com',
    storageBucket: 'productivitwo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJBgZj1ocI9nTlskrpk__9g7KWD5oqvU',
    appId: '1:752644759129:ios:a108b3fc11c5e72c411b48',
    messagingSenderId: '752644759129',
    projectId: 'productivitwo-app',
    storageBucket: 'productivitwo-app.firebasestorage.app',
    iosBundleId: 'com.madabinghy.productivitwo',
  );

}